version: "3.7"

services:
  fhir-db:
    container_name: fhir-gw-db
    networks:
      - hbBackend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir

networks:
  hbBackend:
    external: true
    name: hbBackend